#![no_std]
#![no_main]

use rmk::macros::rmk_keyboard;

mod mode_oled_renderer;
mod pointing_mode_controller;

// Vial config is automatically generated by `build.rs`, according to `vial.json`
// Please put `vial.json` at your project's root
#[rmk_keyboard]
mod keyboard {
    #[register_processor(event)]
    fn pointing_mode_controller(
        keymap: &'static rmk::keymap::KeyMap<'static>,
    ) -> crate::pointing_mode_controller::PointingModeController<'static> {
        crate::pointing_mode_controller::PointingModeController::new(&keymap)
    }
}
